import { useState } from "react";

function App() {
	const [prompt, setPrompt] = useState("");
	const [imageUrl, setImageUrl] = useState(null);
	const [loading, setLoading] = useState(false);
	const [imgDescription, setImgDescription] = useState(null);

	const requestImage = async (e) => {
		e.preventDefault();

		try {
			setLoading(true);
			const response = await fetch("http://localhost:5500/openai", {
				method: "POST",
				headers: {
					"Content-Type": "application/json"
				},
				body: JSON.stringify({ prompt })
			});

			if (!response.ok) {
				throw new Error("Error al generar la imagen");
			}
			const data = await response.json();
			setImageUrl(data.data);
			setImgDescription(imgDescription);
		} catch (error) {
			console.error(error);
		} finally {
			setLoading(false);
			setPrompt("");
		}
	};

	return (
		<div className="container mx-auto max-w-5xl m-10 p-4">
			<form onSubmit={requestImage}>
				<div className="flex flex-col text-center">
					<label className="text-xl font-bold">
						¿Qué buscas, lo puedo crear por ti?
					</label>
					<textarea
						className="border-2 border-gray-300 p-1 m-2 w-1/2 mx-auto"
						type="text"
						value={prompt}
						onChange={(e) => setPrompt(e.target.value)}
					/>
					<input
						className="bg-gray-500 w-1/2 mx-auto text-white m-4 rounded"
						type="submit"
						value={loading ? "Generando..." : "Generar Imagen"}
					/>
				</div>
			</form>
			{imageUrl && (
				<div className="mt-4">
					<img
						src={imageUrl}
						className="border mx-auto"
						alt="generated by openai"
					/>
				</div>
			)}
		</div>
	);
}

export default App;
